---

# Variables setup
- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

# Install the Commercially Supported Docker Engine
- include: install_csengine.yml

# Setup the Docker Universal Control Plane Cluster
- include: setup_ucp_cluster.yml
